### ISSUE TITLE
'LangCellDataCollatorForCellClassification' object has no attribute 'add_cls'

### ISSUE THREAD

**Issue by weiiioyo** [PharMolix/LangCell#2]
您好，
    最近我尝试跟着LangCell的zero-short.ipynb教程运行LangCell，但是出现了如下报错：
    AttributeError: 'LangCellDataCollatorForCellClassification' object has no attribute 'add_cls'

以下是我运行的代码以及详细的报错信息，能请您的团队帮忙看看是哪里出了问题吗？
[zero-shot-test.html.zip](https://github.com/PharMolix/LangCell/files/15375020/zero-shot-test.html.zip)

**Comment by toycat-I** [comment]
我们已经在当前版本中修复这项bug。感谢您对LangCell的兴趣，以及对完善该项目做出的帮助！
