### ISSUE TITLE
Request for Textual Annotations File for Applying LangCell to New Datasets

### ISSUE THREAD

**Issue by yeqing97** [PharMolix/LangCell#3]
Hello,

First, thank you for your excellent work on LangCell. We are currently working on applying LangCell to new datasets for cell annotation. To proceed, we require the textual annotations file, which appears to be missing from the provided resources.

Could you please provide the necessary textual annotations file or guide us on how to generate or obtain it? Any assistance or direction you can provide would be greatly appreciated.

Thank you for your time and help.

**Comment by toycat-I** [comment]
Thank you for your interest in LangCell! We have now uploaded the OBO Foundry file "obo.json" [here](https://drive.google.com/drive/folders/1cuhVG9v0YoAnjW-t_WMpQQguajumCBTp), which contains textual descriptions of common cell identities. You can use these as examples to write textual descriptions for new cell types.
