### ISSUE TITLE
Will you release the scLibrary dataset?

### ISSUE THREAD

**Issue by syr-cn** [PharMolix/LangCell#7]
Thanks for your excellent work.

The paper says you've established a new dataset scLibrary with 27.5M rna-text pairs. Do you have any plans to release it?
If there's any copyright issue, could you release the code about retrieving the data?

**Comment by toycat-I** [comment]
Thank you very much for your interest in and support of our work. We have released the scLibrary dataset. it can be downloaded  [here](https://huggingface.co/datasets/Toycat/scLibrary/tree/main).
