### ISSUE TITLE
pip install -r requirements.txt ERROR

### ISSUE THREAD

**Issue by xhl-xhl** [PharMolix/LangCell#8]
ERROR: Could not find a version that satisfies the requirement geneformer==0.0.1 (from versions: none)
ERROR: No matching distribution found for geneformer==0.0.1

**Comment by scrab017** [comment]
yup, same error. After installing geneformer from https://geneformer.readthedocs.io/en/latest/getstarted.html, getting the following error: ImportError: cannot import name 'token_dictionary' from 'geneformer.pretrainer' (/home/scrab017/miniforge3/envs/scRNAprojC/lib/python3.10/site-packages/geneformer/pretrainer.py)

**Comment by toycat-I** [comment]
Thank you for your attention to our work!
We noticed that the publisher of Geneformer has removed the compatibility with langcell 0.0.1 version, so we have added the geneformer-0.0.1 package in the updates to this GitHub repository. You can install it by cloning this repository and following these steps:
cd geneformer_001
pip install .
